# Generated by Django 5.2.1 on 2025-05-21 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('trimestre', models.CharField(choices=[('PRIMERO', 'Primer Trimestre'), ('SEGUNDO', 'Segundo Trimestre'), ('TERCERO', 'Tercer Trimestre')], max_length=10)),
                ('año_academico', models.CharField(help_text='Formato: AAAA-AAAA (ej: 2024-2025)', max_length=9)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'unique_together': {('trimestre', 'año_academico')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_puntaje', models.DecimalField(decimal_places=2, help_text='Asistencia, disciplina (10 puntos)', max_digits=4)),
                ('saber_puntaje', models.DecimalField(decimal_places=2, help_text='Exámenes (35 puntos)', max_digits=4)),
                ('hacer_puntaje', models.DecimalField(decimal_places=2, help_text='Tareas, prácticos (35 puntos)', max_digits=4)),
                ('decidir_puntaje', models.DecimalField(decimal_places=2, help_text='Promedio entre saber y hacer (10 puntos)', max_digits=4)),
                ('autoevaluacion_puntaje', models.DecimalField(decimal_places=2, help_text='Autoevaluación del estudiante (10 puntos)', max_digits=4)),
                ('nota_total', models.DecimalField(decimal_places=2, help_text='Suma de todos los componentes (100 puntos)', max_digits=5)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'role': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.periodo')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'unique_together': {('estudiante', 'materia', 'periodo')},
            },
        ),
    ]
