# Generated by Django 5.2.1 on 2025-05-21 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='ultima_actualizacion',
            new_name='ultima_modificacion',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='autoevaluacion_puntaje',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota_total',
        ),
        migrations.AddField(
            model_name='nota',
            name='autoevaluacion_decidir',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Autoevaluación del estudiante para el decidir (0-5 puntos)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='nota',
            name='autoevaluacion_ser',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Autoevaluación del estudiante para el ser (0-5 puntos)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='decidir_puntaje',
            field=models.DecimalField(decimal_places=2, help_text='Promedio de ser, saber y hacer (10 puntos)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='hacer_puntaje',
            field=models.DecimalField(decimal_places=2, help_text='Tareas, prácticos (35 puntos)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='saber_puntaje',
            field=models.DecimalField(decimal_places=2, help_text='Exámenes (35 puntos)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='ser_puntaje',
            field=models.DecimalField(decimal_places=2, help_text='Asistencia, disciplina, participaciones (10 puntos)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
