[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y python3 python3-pip && cd backend && pip3 install -r requirements.txt && python3 manage.py collectstatic --noinput"

[deploy]
startCommand = "cd backend && gunicorn aula_inteligente.wsgi --log-file -"
healthcheckPath = "/"
healthcheckTimeout = 300

[phases.setup]
nixPkgs = ["python311", "postgresql", "python311Packages.pip"]

[nixpacks]
python-version = "3.11"
