# Generated by Django 5.2.1 on 2025-05-21 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Curso al que pertenece el estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='cursos.curso'),
        ),
    ]
