# Generated by Django 5.2.1 on 2025-05-21 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('valor_numerico', models.DecimalField(decimal_places=2, help_text='Valor numérico predicho', max_digits=4)),
                ('nivel_rendimiento', models.CharField(choices=[('BAJO', 'Rendimiento Bajo'), ('MEDIO', 'Rendimiento Medio'), ('ALTO', 'Rendimiento Alto')], max_length=10)),
                ('promedio_notas', models.DecimalField(decimal_places=2, help_text='Promedio de notas usado para predecir', max_digits=4)),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, help_text='Porcentaje de asistencia usado para predecir', max_digits=5)),
                ('promedio_participaciones', models.DecimalField(decimal_places=2, help_text='Promedio de participaciones usado para predecir', max_digits=4)),
                ('estudiante', models.ForeignKey(limit_choices_to={'role': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
            },
        ),
    ]
