# Generated by Django 5.2.1 on 2025-05-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccion',
            name='confianza',
            field=models.IntegerField(default=80, help_text='Nivel de confianza de la predicción (porcentaje)'),
        ),
    ]
