# Generated by Django 5.2.1 on 2025-05-21 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('VOLUNTARIA', 'Participación Voluntaria'), ('SOLICITADA', 'Participación Solicitada'), ('EJERCICIO', 'Resolución de Ejercicio'), ('PRESENTACION', 'Presentación'), ('DEBATE', 'Participación en Debate')], default='VOLUNTARIA', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.PositiveSmallIntegerField(help_text='Valor de 1 a 10 que califica la calidad de la participación')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
            },
        ),
    ]
