# Generated by Django 5.2.1 on 2025-05-25 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia_profesor'),
        ('participaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacion',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='tipo',
            field=models.CharField(choices=[('VOLUNTARIA', 'Participación Voluntaria'), ('SOLICITADA', 'Participación Solicitada'), ('EJERCICIO', 'Resolución de Ejercicio'), ('PRESENTACION', 'Presentación'), ('DEBATE', 'Participación en Debate')], db_index=True, default='VOLUNTARIA', max_length=20),
        ),
        migrations.AddIndex(
            model_name='participacion',
            index=models.Index(fields=['estudiante', 'materia'], name='participaci_estudia_904200_idx'),
        ),
        migrations.AddIndex(
            model_name='participacion',
            index=models.Index(fields=['fecha'], name='participaci_fecha_37dfd8_idx'),
        ),
    ]
