# Generated by Django 5.2.1 on 2025-05-24 02:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título breve de la notificación', max_length=100)),
                ('mensaje', models.TextField(help_text='Contenido completo de la notificación')),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('ALERTA', 'Alerta'), ('PREDICCION', 'Predicción'), ('RECORDATORIO', 'Recordatorio'), ('SISTEMA', 'Sistema')], default='INFO', help_text='Categoría de la notificación', max_length=15)),
                ('estado', models.CharField(choices=[('NO_LEIDA', 'No Leída'), ('LEIDA', 'Leída'), ('ARCHIVADA', 'Archivada')], default='NO_LEIDA', help_text='Estado de la notificación', max_length=15)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación de la notificación')),
                ('fecha_lectura', models.DateTimeField(blank=True, help_text='Fecha y hora en que se leyó la notificación', null=True)),
                ('url_accion', models.CharField(blank=True, help_text='URL opcional para dirigir al usuario a una acción específica', max_length=255, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario destinatario de la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
