# Generated by Django 5.2.1 on 2025-05-21 19:53

import apps.materias.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_impartidas', to=settings.AUTH_USER_MODEL, validators=[apps.materias.models.validar_profesor]),
        ),
    ]
